# _Transposed Convolutions_
## based on the tutorial ["Up-sampling with Transposed Convolution"](https://medium.com/activating-robotic-minds/up-sampling-with-transposed-convolution-9ae4f2df52d0) by Naoki Shibuya

In [1]:
import numpy as np

Define a $4x4$ input matrix $M$.

In [2]:
M = np.array([[4,5,8,7],
              [1,8,8,8],
              [3,6,6,4],
              [6,5,7,8]])
M

array([[4, 5, 8, 7],
       [1, 8, 8, 8],
       [3, 6, 6, 4],
       [6, 5, 7, 8]])

Define a $3x3$ kernel matrix.

In [3]:
K = np.array([[1,4,1],
              [1,4,3],
              [3,3,1]])
K

array([[1, 4, 1],
       [1, 4, 3],
       [3, 3, 1]])

Define the convolutional matrix resulting from applying this $3x3$ kernel with stride = $1$ and no padding.

In total there will be $4$ convolutions with $16$ multiplications per convolution.

In [4]:
C = np.array([[1,4,1,0,1,4,3,0,3,3,1,0,0,0,0,0],
              [0,1,4,1,0,1,4,3,0,3,3,1,0,0,0,0],
              [0,0,0,0,1,4,1,0,1,4,3,0,3,3,1,0],
              [0,0,0,0,0,1,4,1,0,1,4,3,0,3,3,1]])
C

array([[1, 4, 1, 0, 1, 4, 3, 0, 3, 3, 1, 0, 0, 0, 0, 0],
       [0, 1, 4, 1, 0, 1, 4, 3, 0, 3, 3, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 4, 1, 0, 1, 4, 3, 0, 3, 3, 1, 0],
       [0, 0, 0, 0, 0, 1, 4, 1, 0, 1, 4, 3, 0, 3, 3, 1]])

In [5]:
C.shape

(4, 16)

Calculate the output $2x2$ output matrix $D$ resulting from applying convolution matrix $C$ to input matrix $M$ (reshaped to $16x1$).

$$D_{(4x1)} = C_{(4x16)} \times M_{(16x1)}$$

In [6]:
# reshape input to 9x1
M = M.reshape(16,1)

# applying convolution
D = np.matmul(C, M).reshape(2,2)
D

array([[122, 148],
       [126, 134]])

Create the transpose convolutional matrix $C^T$

In [7]:
C_t = np.transpose(C)
C_t

array([[1, 0, 0, 0],
       [4, 1, 0, 0],
       [1, 4, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 1, 0],
       [4, 1, 4, 1],
       [3, 4, 1, 4],
       [0, 3, 0, 1],
       [3, 0, 1, 0],
       [3, 3, 4, 1],
       [1, 3, 3, 4],
       [0, 1, 0, 3],
       [0, 0, 3, 0],
       [0, 0, 3, 3],
       [0, 0, 1, 3],
       [0, 0, 0, 1]])

**Up-Sample** using transpose convolutional matrix $C^T$.

$$U_{(16x1)} = C^T_{(16x4)} \times M_{(4x1)}$$

In [8]:
M = np.array([2,1,4,4])
U = np.matmul(C_t, M).reshape(4,4)
U

array([[ 2,  9,  6,  1],
       [ 6, 29, 30,  7],
       [10, 29, 33, 13],
       [12, 24, 16,  4]])